#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#
#  [plugins.build]
#  windows = 'tools\\update-dll-mingw'
#  cygwin = 'make -f make_cygwin.mak'
#  mac = 'make -f make_mac.mak'
#  unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'rhysd/unite-codic.vim'

[[plugins]]
repo = 'koron/codic-vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#[[plugins]]
#repo = 'Shougo/unite-outline'

# Color Scheme
[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tyru/caw.vim'

# [[plugins]]
# repo = 'tomtom/tcomment_vim'

# change string next order
[[plugins]]
repo = 'nishigori/increment-activator'

# interactive string replace
[[plugins]]
repo = 'osyo-manga/vim-over'

# Quickrun - outputter
[[plugins]]
repo = 'osyo-manga/quickrun-outputter-replace_region'

[[plugins]]
repo = 'majutsushi/tagbar'

#[[plugins]]
#repo = 'Lokaltog/vim-easymotion'

#[[plugins]]
#repo = 'bronson/vim-trailing-whitespace'

#[[plugins]]
#repo = 'thinca/vim-fontzoom'

#[[plugins]]
#repo = 'mattn/benchvimrc-vim'

# syntax cheker
[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['osyo-manga/shabadou.vim', 'cohama/vim-hier']
filetypes = 'all'

